---

- name: Install CUL Flash Support
  apt: name={{ item }} state=latest force=yes
  with_items:
    - make
    - dfu-programmer
  when: _fhem.firware_flash_support

- name: Add Fhem APT Repository Key
  apt_key: url=https://debian.fhem.de/archive.key state=present

- name: Add Fhem APT Repository
  apt_repository: repo="deb https://debian.fhem.de/stable ./" state=present update_cache=yes

- name: Install Fhem
  apt: name={{ item }} state=latest force=yes
  with_items:
    - make
    - dfu-programmer
    - fhem
    - libjson-perl
    - sysstat
    - libsys-statistics-linux-perl
  register: installation_changed

- name: Update Fhem
  command: /opt/fhem/fhem.pl localhost:7072 update
  when: update_fhem is defined
  notify:
    - Restart Fhem

- name: Stop Fhem after Installation
  service: name=fhem state=stopped
  when: installation_changed|changed or clean_fhem_saved_state is defined and clean_fhem_saved_state
  notify:
    - Restart Fhem

- name: Remove Fhem Saved State
  file: name=/opt/fhem/log/fhem.save state=absent
  when: clean_fhem_saved_state|default(False)|bool
  notify:
    - Restart Fhem

- name: Create GNUplot Files
  template: src='opt/fhem/www/gplot/{{ item.value.template }}' dest='/opt/fhem/www/gplot/{{ item.key }}.gplot' owner=fhem group=dialout mode=0600
  with_dict: "{{ _fhem.plots.templates }}"

- name: Copy GNUplot Files
  copy: src='opt/fhem/www/gplot/{{ item }}' dest='/opt/fhem/www/gplot/{{ item }}' owner=fhem group=dialout mode=0600
  with_items: "{{ _fhem.plots.files }}"

- name: Create Fhem Configuration
  template: src='{{ item }}.j2' dest='/{{ item }}' owner=fhem group=dialout mode=0600
  with_items:
    - opt/fhem/fhem.cfg
  notify:
    - Restart Fhem


